### ISSUE TITLE
Essentials problem with Tshock for 1.2.1.1 V0.3

### ISSUE THREAD

**Issue by Kro55f1r3** [Scavenger3/Essentials-SignCommands#3]
[Server API] Warning plugin "Essentials" has had an unhandled exception throw by one of ths gameupdate handlers
System.missingmethodexception : Missing Methode : 'Void TshockAPI.TSPlayer.Disable(system.string)
 at Essentials.essentials.Onupdate(eventargs args
at TerrariaAPI.server.handlerCollection"1.invoke(Argstype Args)

**Comment by Scavenger3** [comment]
This was fixed in the last commit... Tested with TShock Pre-release v0.3 for Terraria 1.2.1.1 no issues... try re-downloading the dlls.
